version: '3.8'

networks:
  frontend:
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./shared_volume:/var/hosts
    networks:
      frontend:
    deploy:
      mode: replicated
      replicas: 3
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./shared_volume:/var/hosts
    networks:
      frontend:
    deploy:
      mode: replicated
      replicas: 2
